/**
 * Standardized API error codes.
 *
 * Every error response from the API follows this shape:
 *   { success: false, error: { code: string, message: string, details?: object } }
 *
 * Import this enum anywhere you construct or handle API errors.
 */

export const ErrorCode = {
  // Auth (4xx)
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  TWO_FACTOR_REQUIRED: "TWO_FACTOR_REQUIRED",

  // Validation (4xx)
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_INPUT: "INVALID_INPUT",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",

  // Resource (4xx)
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",

  // Rate limiting (4xx)
  RATE_LIMITED: "RATE_LIMITED",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  TOO_MANY_AUTH_ATTEMPTS: "TOO_MANY_AUTH_ATTEMPTS",
  OTP_COOLDOWN: "OTP_COOLDOWN",

  // Idempotency (4xx)
  IDEMPOTENCY_KEY_CONFLICT: "IDEMPOTENCY_KEY_CONFLICT",
  MISSING_IDEMPOTENCY_KEY: "MISSING_IDEMPOTENCY_KEY",
  INVALID_IDEMPOTENCY_KEY: "INVALID_IDEMPOTENCY_KEY",

  // Billing (4xx)
  FEATURE_LOCKED: "FEATURE_LOCKED",
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",
  PLAN_LIMIT_REACHED: "PLAN_LIMIT_REACHED",
  TRIAL_EXPIRED: "TRIAL_EXPIRED",
  INVOICE_PAYMENT_FAILED: "INVOICE_PAYMENT_FAILED",

  // Financial (4xx)
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  TRANSACTION_LIMIT_EXCEEDED: "TRANSACTION_LIMIT_EXCEEDED",
  INVALID_AMOUNT: "INVALID_AMOUNT",
  PAYOUT_BLOCKED: "PAYOUT_BLOCKED",
  CHAMA_FROZEN: "CHAMA_FROZEN",
  MULTISIG_REQUIRED: "MULTISIG_REQUIRED",

  // KYC / Compliance (4xx)
  KYC_REQUIRED: "KYC_REQUIRED",
  KYC_LEVEL_INSUFFICIENT: "KYC_LEVEL_INSUFFICIENT",
  KYC_DOCUMENT_REJECTED: "KYC_DOCUMENT_REJECTED",
  AML_SCREEN_FAILED: "AML_SCREEN_FAILED",
  SANCTIONS_MATCH: "SANCTIONS_MATCH",

  // Payment provider (4xx/5xx)
  MPESA_ERROR: "MPESA_ERROR",
  MPESA_TIMEOUT: "MPESA_TIMEOUT",
  FLUTTERWAVE_ERROR: "FLUTTERWAVE_ERROR",
  STRIPE_ERROR: "STRIPE_ERROR",
  PAYMENT_PROVIDER_UNAVAILABLE: "PAYMENT_PROVIDER_UNAVAILABLE",

  // Server (5xx)
  INTERNAL_ERROR: "INTERNAL_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
  REDIS_ERROR: "REDIS_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",

  // Webhook
  INVALID_WEBHOOK_SIGNATURE: "INVALID_WEBHOOK_SIGNATURE",
  WEBHOOK_IP_NOT_ALLOWED: "WEBHOOK_IP_NOT_ALLOWED",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

/**
 * HTTP status code mapping for every error code.
 */
export const ErrorCodeStatus: Record<string, number> = {
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  TOKEN_EXPIRED: 401,
  INVALID_CREDENTIALS: 401,
  EMAIL_NOT_VERIFIED: 403,
  TWO_FACTOR_REQUIRED: 401,

  VALIDATION_ERROR: 400,
  INVALID_INPUT: 400,
  MISSING_REQUIRED_FIELD: 400,

  NOT_FOUND: 404,
  CONFLICT: 409,
  ALREADY_EXISTS: 409,
  DUPLICATE_ENTRY: 409,

  RATE_LIMITED: 429,
  TOO_MANY_REQUESTS: 429,
  TOO_MANY_AUTH_ATTEMPTS: 429,
  OTP_COOLDOWN: 429,

  IDEMPOTENCY_KEY_CONFLICT: 422,
  MISSING_IDEMPOTENCY_KEY: 400,
  INVALID_IDEMPOTENCY_KEY: 400,

  FEATURE_LOCKED: 402,
  PAYMENT_REQUIRED: 402,
  PLAN_LIMIT_REACHED: 402,
  TRIAL_EXPIRED: 402,
  INVOICE_PAYMENT_FAILED: 402,

  INSUFFICIENT_FUNDS: 422,
  TRANSACTION_LIMIT_EXCEEDED: 422,
  INVALID_AMOUNT: 400,
  PAYOUT_BLOCKED: 422,
  CHAMA_FROZEN: 423,
  MULTISIG_REQUIRED: 422,

  KYC_REQUIRED: 403,
  KYC_LEVEL_INSUFFICIENT: 403,
  KYC_DOCUMENT_REJECTED: 422,
  AML_SCREEN_FAILED: 403,
  SANCTIONS_MATCH: 403,

  MPESA_ERROR: 502,
  MPESA_TIMEOUT: 504,
  FLUTTERWAVE_ERROR: 502,
  STRIPE_ERROR: 502,
  PAYMENT_PROVIDER_UNAVAILABLE: 503,

  INTERNAL_ERROR: 500,
  DATABASE_ERROR: 500,
  REDIS_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
  EXTERNAL_SERVICE_ERROR: 502,

  INVALID_WEBHOOK_SIGNATURE: 401,
  WEBHOOK_IP_NOT_ALLOWED: 403,
};
